

BattleDefine = {
    ROUND_STEP_START = 1,
    ROUND_STEP_FINISH = 2,
    ROUND_STEP_GEN_ACTION = 3,
    ROUND_STEP_WAIT_ACTION = 4,
    ROUND_STEP_ERROR = -1,
    
    RULE_PLAYER_COUNT = 1,
    RULE_PLAYER_FIRST = 2,

    RULE_CARD_COUNT = 3,


    ACTION_ERROR = -1,
    ACTION_GAME_START = 0,
    ACTION_GAME_FINISH = 1,
}
